### ISSUE TITLE
passing the store as prop

### ISSUE THREAD

**Issue by eecolella** [floating/restore#12]
Hi,

Very interesting project, it eliminates a lot of redux boilerplate.

I have a little concern, why your connect hoc is adding the store on the component object and not passing it as prop?

I think it is a quite standard convention. An example will be quite problematic composing your hoc with other hocs (like the library recompose)

Regards,

E.

**Comment by floating** [comment]
Hey E, thanks for your interest in the project.  

The `store` is added to the component object because it’s designed to be a peer of `this.state`  and `this.props`. I think it’s beneficial to think about them as three independent ways to interface with data in your components, each of which is useful in different cases. It’s a cleaner interface in that regard not to nest them. Also, Restore currently isn’t using a HOC pattern do this, it’s extending your component directly with a small bit of functionality to make it observable and add the `store`.

That being said I’m highly interested in making sure Restore is compatible with any of the ways you’re thinking about using it. I’d love to see any examples of what you’re hoping to do with it that it may not currently support.

Jordan
